export const OTHER_SECTOR = "Otro";
export const OTHER_CITY = "Otra";

const lists: Record<string, string[]> = {
  Baní: [
    "Centro",
    "Pueblo Arriba",
    "Pueblo Abajo",
    "El Fundo",
    "Pueblo Nuevo",
    "Mejoramiento Social",
    "Villa Majega",
    "Los Pescadores",
    "Santa Rosa",
    "30 de Mayo",
    "19 de Marzo",
  ],
  Bonao: [
    "Centro",
    "Los Multis",
    "El Tanque",
    "Villa de la Cruz",
    "Pueblo Nuevo",
    "Mejoramiento Social",
    "Las Delicias",
    "Los Transformadores",
  ],
  Cabarete: [
    "Cabarete",
    "Encuentro",
    "Kite Beach",
    "La Goleta",
    "Perla Marina",
    "Ocean Dream",
  ],
  Cabrera: [
    "Centro",
    "El Calvario",
    "La Entrada",
    "Abreu",
    "Lope de Vega",
    "Pueblo Nuevo",
  ],
  Constanza: [
    "Centro",
    "El Castillo",
    "Las Auyamas",
    "Los Almendros",
    "Tireo",
    "Pueblo Nuevo",
  ],
  "El Seibo": [
    "Centro",
    "Santa Cruz",
    "Pueblo Nuevo",
    "Mejoramiento Social",
    "Villa Guerrero",
  ],
  "Gaspar Hernández": [
    "Centro",
    "La Jagua",
    "El Jobo",
    "Río Arriba",
    "Jamao",
    "Pueblo Nuevo",
  ],
  "Hato Mayor": [
    "Centro",
    "Pueblo Nuevo",
    "Mejoramiento Social",
    "Los Solares",
    "Yerba Buena",
  ],
  "La Romana": [
    "Centro",
    "Caleta",
    "Savica",
    "Villa Progreso",
    "Enriquillo",
    "Padre Eterno",
    "Pueblo Nuevo",
    "Santa Rosa",
    "San Carlos",
    "Quisqueya",
  ],
  "La Vega": [
    "Centro",
    "Don Bosco",
    "Palmarito",
    "Mejoramiento Social",
    "Las Carolinas",
    "El Naranjal",
    "Villa Francisca",
    "Los Pomos",
  ],
  Moca: [
    "Centro",
    "Pueblo Nuevo",
    "Mejoramiento Social",
    "La Guázara",
    "El Tanque",
    "Los Transformadores",
  ],
  Montellano: ["Centro", "El Mamey", "Los Cacaos", "Pueblo Nuevo"],
  "Puerto Plata": [
    "Centro",
    "Padres Las Casas",
    "Costambar",
    "Playa Dorada",
    "Los Caciques",
    "Domínico",
    "La Lealtad",
    "El Cupey",
  ],
  "Río San Juan": [
    "Centro",
    "El Caliche",
    "La Playita",
    "Los Tocones",
    "Pueblo Nuevo",
  ],
  Samaná: [
    "Centro",
    "Los Cacaos",
    "El Valle",
    "La Churcha",
    "Las Flechas",
    "Santa Bárbara",
  ],
  "San Cristóbal": [
    "Centro",
    "Pueblo Nuevo",
    "La Pólvora",
    "Madre Vieja Norte",
    "Madre Vieja Sur",
    "La Suiza",
    "Mejoramiento Social",
  ],
  Sosúa: [
    "El Batey",
    "Los Charamicos",
    "Sosúa Abajo",
    "Sosúa Arriba",
    "Puerto Chiquito",
    "La Mulata",
  ],
  Tenares: ["Centro", "Blanco", "Jamao", "Pueblo Nuevo"],
  Veragua: ["Centro", "Veragua Arriba", "Veragua Abajo", "La Jagua"],
};

export function sectorsFor(city: string): string[] {
  const list = lists[city] ?? ["Centro"];
  return [...list, OTHER_SECTOR];
}
